### ISSUE TITLE
Use client side storage for caching images and XML and use LastModified info to refresh them

### ISSUE THREAD

**Issue by shivahr** [MILE-IISc/ocr-web-app#24]
Web Storage API
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API

HTML5 Local Storage
https://www.w3schools.com/html/html5_webstorage.asp

What is the max size of localStorage values?
https://stackoverflow.com/questions/2989284/what-is-the-max-size-of-localstorage-values

Test of localStorage limits/quota
https://arty.name/localstorage.html

HTML5 Local Storage
http://tutorials.jenkov.com/html5/local-storage.html

**Comment by Sasi5875** [comment]
IndexedDB API
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

Storing images and files in IndexedDB
https://hacks.mozilla.org/2012/02/storing-images-and-files-in-indexeddb/

PouchDB
https://pouchdb.com/learn.html

**Comment by Sasi5875** [comment]
IndexedDB with usability - This is a tiny (~1.09k brotli'd) library that mostly mirrors the IndexedDB API, but with small improvements that make a big difference to usability.
https://www.npmjs.com/package/idb

localForage is a fast and simple storage library for JavaScript. localForage improves the offline experience of your web app by using asynchronous storage (IndexedDB or WebSQL) with a simple, localStorage-like API.
https://www.npmjs.com/package/localforage

**Comment by Sasi5875** [comment]
Storage for the web - There are several ways to cache your static application resources (HTML, JavaScript, CSS, images, etc.), and data (user data, news articles, etc.). But which is the best solution? How much can you store? How do you prevent it from being evicted?
https://web.dev/storage-for-the-web/
